export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
